### ISSUE TITLE
announcementコンポーネントのキャッシュバグ

### ISSUE THREAD

**Issue by Na0ki** [lindwurm/mastodon#18]
焼きましておめでとうございます。

このインスタンスの [announcements](https://github.com/lindwurm/mastodon/blob/hota/master/app/javascript/mastodon/features/compose/components/announcements.js)を~~パク~~参考にする際にバグを発見したのでご報告します。

static変数が [51-53行目](https://github.com/lindwurm/mastodon/blob/hota/master/app/javascript/mastodon/features/compose/components/announcements.js#L51-L53) で定義されていますが、これを呼び出す際のクラス名を間違えており参照されていなかったです。
これによりキャッシュが一切効いておらず、毎回新規でお知らせを取得している状態です。

パッチを添付したので詳しくはそちらを参照してください。

***

拡張子が .patch のファイルを添付できなかったので、 .txt を追加してアップしてます。
お手元で試す場合は .txt を外してください。

[0001-typo-static.patch.txt](https://github.com/lindwurm/mastodon/files/1521485/0001-typo-static.patch.txt)

**Comment by unarist** [comment]
ほげー。どうも犯人です ( https://github.com/unarist/mastodon/compare/1306d63...mod/announcements )。

とはいえそれは定義というより初期化というだけで、ないならないでundefinedになります。そしてfalseやnullと厳密な比較をしている箇所はないので、当方の環境では期待通りに動作しているように見えます。

このMODのキャッシュはあくまで304やエラーで空レスポンスを受けとった時に代わりに表示するためだけのもので、基本的には毎回fetchを行ないます。その際、サーバー側で max-age 等が指定されていればそれに（ブラウザが）従いますが、なければ `If-Modified-Since` をつけてリクエストを行います。

サーバー側から通知を行うことなく、かつクライアントも開いたまま、お知らせを更新できるようにということでこのような仕様になっています。

**Comment by Na0ki** [comment]
なるほど

確かにfetchに支障はないようです。
より厳密に動作させるにはAnnouncementsにしてキャッシュ制御するか、そもそも変数自体を無くしてしまったほうがいい感じですかね。（いずれの変更も動作上あまり現状と変わらなさそうですが）

キャッシュ制御をそれほど行ったことがなかったので勉強になりました。

**Comment by unarist** [comment]
多分、動作は全く変わりません。とはいえ書くべきと思って書いたものですから、ご指摘いただいた修正は正しいです…（そのうち）直しておきますね。

見つけていただいてありがとうございます🙏
